spring.application.name=carpinteria

# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/carpinteriadb?useSSL=false&serverTimezone=America/La_Paz&allowPublicKeyRetrieval=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Carpinteria2025!

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Filtro para soportar metodos PUT y DELETE desde formularios HTML
spring.mvc.hiddenmethod.filter.enabled=true

server.port=8080
